name: gee_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - gdal
  - rasterio
  - geopandas
  - shapely
  - pyproj
  - fiona
  - rtree
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - notebook
  - ipykernel